import Head from 'next/head';

export default function Test() {
  return (
    <div>
      <Head>
        <title>Thread Affair</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon" href="/favicon.ico"></link>
      </Head>
      Hello
      <i className="fa-solid fa-phone"></i>
      <button className="button">test</button>
      <button className="button button-large">test large</button>
      <a href="" className="button">
        test
      </a>
      <a href="" className="button button-large">
        test large
      </a>
      <div className="mt-4">
        <span className="badge">-50%</span>
        <span className="badge badge-font-large">%</span>
        <span className="badge badge-secondary">new entry</span>
        <span className="badge badge-secondary badge badge-font-large">
          -5%
        </span>
      </div>
    </div>
  );
}
